MAX_WIDTH = 1280
MAX_HEIGHT = 720

DINO_WIDTH = 32
DINO_HEIGHT = 32

LINE_POSITION_Y = MAX_HEIGHT // 2 + DINO_HEIGHT

PEBBLE_HEIGHT_RANGE = (2, 5)
PEBBLE_WIDTH_RANGE = (5, 10)

PEBBLE_Y = LINE_POSITION_Y + 1
PEBBLE_X_RANGE = (0, MAX_WIDTH)

NUM_PEBBLES = 80